name: Deploy Lambda Layer (Python 3.13) via Docker

on:
  push:
    branches:
      - main
    # paths:
      # - 'requirements.txt'
      # - 'payrollConsumer/requirements.txt'

env:
  LAYER_NAME: custom-python-3-13-layer
  AWS_REGION: us-east-1 # Altere para a sua região
  LAMBDA_RUNTIME_IMAGE: public.ecr.aws/lambda/python:3.13 # Imagem base oficial do AWS Lambda

  MASTER_DEPLOY_KEY: ${{ secrets.MASTER_DEPLOY_KEY }}
  AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_HOMOLOG }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_HOMOLOG }}
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
  GHCR_USER: ${{ secrets.GHCR_USER }}  

jobs:
  deploy_layer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # # --- 1. CONFIGURAÇÃO AWS ---
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}

      # --- 2. CONSTRUÇÃO DO LAYER COM DOCKER ---
      - name: Build Layer Package inside Docker
        run: |
          # 1. Cria a pasta 'python' que o Lambda Layer espera
          mkdir -p layer_package/python

          # 2. Executa a instalação dentro do contêiner Docker do Lambda
          # ADICIONADO: --entrypoint /bin/bash para evitar o erro do handler
          docker run \
            --rm \
            --entrypoint /bin/bash \
            -v /home/runner/work/lambda-layer/lambda-layer:/var/task \
            -w /var/task \
            public.ecr.aws/lambda/python:3.13 \
            -c "pip install -r payrollConsumer/requirements.txt -t layer_package/python --no-cache-dir"
          # Nota: O comando 'sh -c "..."' foi substituído por '-c "..."' 
          # após a definição do novo entrypoint /bin/bash.

      # --- 3. COMPACTAÇÃO ---
      - name: Zip the layer package
        run: |
          # Compacta o conteúdo da pasta layer_package em layer.zip
          cd layer_package
          zip -r ../layer.zip .
          cd ..

      # --- 4. TEST - DEPLOY COM AWS CLI ---
      - name: Publish Lambda Layer        
        run: |
          aws lambda list-functions \
            --query 'Functions[*].FunctionName' \
            --output text

      # # --- 4. DEPLOY COM AWS CLI ---
      # - name: Publish Lambda Layer
      #   id: publish_layer
      #   run: |
      #     publish_result=$(aws lambda publish-layer-version \
      #       --layer-name ${{ env.LAYER_NAME }} \
      #       --description "Dependencies Python 3.13 (Docker built): boto3, psycopg2-binary" \
      #       --zip-file fileb://layer.zip \
      #       --compatible-runtimes python3.13 \
      #       --query 'LayerVersionArn' \
      #       --output text)

      #     echo "LayerVersionArn=$publish_result" >> $GITHUB_OUTPUT

      # - name: Output Layer ARN
      #   run: echo "Layer ARN: ${{ steps.publish_layer.outputs.LayerVersionArn }}"
